/**
 * Fake PR titles for the Ship step's box-labelling easter egg — see the
 * "PR tag" logic in `FactoryScene.astro`.
 */
export const FAKE_PR_TITLES: string[] = [
  "add cheese",
  "add more cheese",
  "remove cheese, customers complained",
  "ignore customer complaints",
  "add overengineered landing page",
  "fix the fix from yesterday",
  "rename variable for the fourth time",
  "remove that TODO from 2019",
  "bump version, cross fingers",
  "add feature nobody asked for",
  "delete unused code (again)",
  "fix flaky test by adding sleep(5000)",
  "revert revert of revert",
  "add emoji to commit messages",
  "refactor for job security",
  "fix typo in previous fix",
  "add more logging, it'll help this time",
  "disable linter, ship it",
  "hotfix prod on a friday",
  "add dark mode nobody asked for",
  "rewrite in rust (just kidding)",
  "add loading spinner to hide slowness",
  "increase timeout, problem solved",
  "add comment explaining the hack",
  "make button 2px bigger per design",
  "add retry logic, three times should do it",
  "swap library for the other library",
  "add config flag for the config flag",
  "finally fix that bug from three sprints ago",
  "add tests (jk, ship it)",
  "optimize for the demo",
  "add cheese v2",
  "quick fix, do not review too closely",
  "wip (do not merge)",
  "merge wip anyway",
  "add missing semicolon",
  "remove missing semicolon, it was fine",
  "update dependencies, pray nothing breaks",
  "downgrade dependency that broke everything",
  "add try/catch around the whole app",
  "silence the error we don't understand",
  "add cheese to the changelog",
  "rename 'temp' to 'temp2'",
  "delete 'temp2', add 'final_temp'",
  "fix production outage from last commit",
  "add feature flag for the feature flag flag",
  "copy-paste from stack overflow, it works",
  "remove copy-pasted code, write it properly",
  "add cache, forget to invalidate it",
  "invalidate cache manually via ssh",
  "add unit test for the untestable function",
  "mock everything, test nothing",
  "increase font size per CEO's request",
  "revert font size, CEO changed their mind",
  "add loading state to the loading state",
  "fix the fix for the fix",
  "add cheese-based rate limiting",
  "remove rate limiting, cheese wasn't the issue",
  "resize images, break every layout",
  "add favicon nobody will notice",
  "update README, still lying about setup steps",
  "add more cowbell",
];
